version: '3.6'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: unless-stopped

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2222

    ports:
      - "80:80"
      - "2222:22"

    volumes:
      - /opt/docker/gitlab/data:/var/opt/gitlab
      - /opt/docker/gitlab/config:/etc/gitlab
      - /opt/docker/gitlab/logs:/var/log/gitlab

    networks:
      - gitlab-network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: unless-stopped


    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/gitlab/runner:/etc/gitlab-runner

    networks:
      - gitlab-network

networks:
  gitlab-network:
    driver: bridge
