version: '3.6'

services:
  gitlab:
    image: yrzr/gitlab-ce-arm64v8:latest
    container_name: gitlab
    restart: always
    hostname: 'git.arribatt.com'

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.0.1.14'
        letsencrypt['enable'] = true
        letsencrypt['contact_emails'] = ['']
        letsencrypt['auto_renew'] = true

        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = ''
        gitlab_rails['smtp_port'] = 
        gitlab_rails['smtp_user_name'] = ''
        gitlab_rails['smtp_password'] = ''
        gitlab_rails['smtp_domain'] = ''
        gitlab_rails['smtp_authentication'] = ''
        gitlab_rails['smtp_enable_starttls_auto'] = false

        gitlab_rails['gitlab_shell_ssh_port'] = 2222

        gitlab_rails['backup_path'] = '/var/opt/gitlab/backups'
        gitlab_rails['backup_keep_time'] = 604800

        registry_external_url 'http://10.0.1.14:5050'

    ports:
      - "80:80"
      - "443:443"
      - "1822:22"
      - "5050:5050"

    volumes:
      - /opt/docker/gitlab/config:/etc/gitlab
      - /opt/docker/gitlab/logs:/var/log/gitlab
      - /opt/docker/gitlab/data:/var/opt/gitlab
      - /opt/docker/gitlab/backups:/var/opt/gitlab/backups

    shm_size: '256m'
    networks:
      - gitlab-network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: unless-stopped


    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/gitlab/runner:/etc/gitlab-runner

    networks:
      - gitlab-network

networks:
  gitlab-network:
    driver: bridge
